# Welcome to Jekyll!

# Website settings
title: "Cyrus Kashef"
description: "Personal website of Cyrus Kashef"
keywords: "cyruskashef,python"
baseurl: "/"
url: "http://cyruskashef.github.io"

# author
author:
  name: 'Cyrus'
  first_name: 'Cyrus'
  last_name: 'Kashef'
  email: 'cyrus.kashef3@outlook.com'
  linkedin_username: 'https://www.linkedin.com/in/cyrus-kashef/'
  github_username: 'CyrusKashef'
  head_img: 'resume/images/profile_picture.jpg'
  desc: "I am a Cloud Engineer at Fidelity Investments. I am a passionate Python software developer."